apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-exam2025
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-exam2025
  template:
    metadata:
      labels:
        app: deployment-exam2025
    spec:
      containers:
      - name: exam2025
        image: gcr.io/lab-6-451616/exam2025:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        env:
          - name: GCP_BUCKET_NAME
            value: "REPLACE_BUCKET_NAME"
        livenessProbe:
          initialDelaySeconds: 5
          periodSeconds: 2
          httpGet:
            path: /
            port: 5000


