apiVersion: v1
kind: Service    
metadata:
  name: service-exam2025
spec:
  type: LoadBalancer
  selector:
    app: deployment-exam2025
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000